apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.infra.local:30443
    path: pki/sign/k8s-dot-local
    caBundleSecretRef:
      name: vault-ca-secret
      key: ca.crt
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: pki-issuer
        secretRef:
          name: cert-manager-vault-token
          key: token