# SPDX-License-Identifier: Apache-2.0
architecture: cluster

cluster:
  minInSyncReplicas: 2
  controllers:
    replicaCount: 3
    persistence:
      size: 8Gi
  brokers:
    replicaCount: 3
    persistence:
      size: 50Gi

pdb:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
