# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: valkey
description: Valkey Helm chart for standalone, replication, sentinel, and cluster topologies
type: application
version: 2.0.3
appVersion: "9.1.1"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - valkey
  - cache
  - datastore
  - sentinel
  - cluster
  - database
  - key-value
  - in-memory
  - ha
home: https://helmforge.dev
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/r/valkey/valkey
  - https://github.com/valkey-io/valkey
icon: https://helmforge.dev/icons/charts/valkey.png
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "upgrade to 9.1.1 security release (#883)"
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/links: |
    - name: Official Website
      url: https://valkey.io
    - name: Source
      url: https://github.com/valkey-io/valkey
    - name: Documentation
      url: https://helmforge.dev/docs/charts/valkey
    - name: Chart Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/valkey
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/zookeeper
    - url: https://artifacthub.io/packages/helm/helmforge/uptime-kuma
