apiVersion: v2
name: vault-server
description: HashiCorp Vault Server (Simulating External Vault)
type: application
version: 1.0.0
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.30.0