# SPDX-License-Identifier: Apache-2.0
architecture: cluster

auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: redis-password

cluster:
  nodes: 6
  replicasPerMaster: 1
  persistence:
    enabled: true
    size: 20Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

pdb:
  enabled: true
