architecture: standalone

image:
  repository: docker.io/library/postgres
  tag: "18.4-trixie"
  pullPolicy: IfNotPresent

auth:
  database: "keycloak"
  username: "keycloak"
  password: "KeycloakPassword123!"
  postgresPassword: "SuperAdminPassword123!"

standalone:
  persistence:
    enabled: true
    storageClass: "longhorn-sit"
    size: 2Gi
    accessModes:
      - ReadWriteOnce

# -- Node selector for pod scheduling
nodeSelector: 
  pool: sit
# -- Tolerations for pod scheduling
tolerations: 
  - key: "env"
    operator: "Equal"
    value: "sit"
    effect: "NoSchedule"