{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "kafka.validate" . }}
{{- if not .Values.kraft.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.kraftSecretName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.kraft.existingSecretClusterIdKey }}: {{ include "kafka.clusterId" . | quote }}
  {{- if eq .Values.architecture "cluster" }}
  {{- range $i := until (.Values.cluster.controllers.replicaCount | int) }}
  {{ printf "%s-%d-directory-id" $.Values.kraft.existingSecretControllerDirectoryIdPrefix $i }}: {{ include "kafka.controllerDirectoryId" (dict "root" $ "index" $i) | quote }}
  {{- end }}
  {{- end }}
{{- end }}
