{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.metrics.enabled }}
{{- if eq .Values.architecture "single-broker" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.singleMetricsServiceName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: single-broker
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.controllerMetricsServiceName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.brokerMetricsServiceName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
{{- end }}
