env: sit
replicaCount: 3

image:
  repository: tondychiu/lotto-backend
  tag: 6182eb3744dbeb7dd8e3fe127a8ff2cde6d70293

nodeSelector:
  pool: sit

tolerations:
  - key: "env"
    operator: "Equal"
    value: "sit"
    effect: "NoSchedule"

podAnnotations:

  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "my-app-sit-role"
  vault.hashicorp.com/namespace: "admin"

  vault.hashicorp.com/tls-skip-verify: "false"
  vault.hashicorp.com/tls-secret: "vault-ca-secret"
  vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"

  vault.hashicorp.com/agent-inject-secret-db-config.properties: "secret/data/sit/my-app"
  vault.hashicorp.com/agent-inject-template-db-config.properties: |
    {{- with secret "secret/data/sit/my-app" -}}
    DB_USER={{ index .Data.data "db-username" }}
    DB_PASS={{ index .Data.data "db-password" }}
    {{- end -}}