apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tondy-reslve/k8s-helm-gitops.git'
    targetRevision: HEAD
    path: infra/vault-issuer
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true