apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tondy-reslve/k8s-helm-gitops.git'
    targetRevision: HEAD
    path: infra/minio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true