{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.pdb.enabled (or (include "redis.isReplication" .) (include "redis.isSentinel" .) (include "redis.isCluster" .)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
{{- end }}
