# SPDX-License-Identifier: Apache-2.0
# CI scenario: explicit auth values without persistence.
# Existing Secret rendering is covered by unit tests; k3d cannot rely on an
# out-of-chart Secret fixture.
auth:
  postgresPassword: helmforge-test-password
  password: helmforge-test-password

standalone:
  persistence:
    enabled: false
