# SPDX-License-Identifier: Apache-2.0
# CI scenario: additional initdb script without external cluster fixtures.
initdb:
  scripts:
    10-extra.sql: |
      SELECT 1;

standalone:
  persistence:
    enabled: false
