# SPDX-License-Identifier: Apache-2.0
# CI scenario: optional External Secrets Operator auth Secret.
# The local k3d lab provides ClusterSecretStore/helmforge-fake-store with
# test/password=helmforge-test-password.
architecture: standalone

auth:
  database: app
  username: app

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  auth:
    enabled: true
    postgresPasswordRemoteRef:
      key: test/password
    userPasswordRemoteRef:
      key: test/password
