# SPDX-License-Identifier: Apache-2.0
architecture: replication

replication:
  primary:
    persistence:
      enabled: false
    probes:
      requireWritable: true
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: false
    probes:
      requireRecoveryMode: true
