# SPDX-License-Identifier: Apache-2.0
architecture: replication

replication:
  primary:
    persistence:
      enabled: false
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: false
  wal:
    keepSize: 2GB
    maxSenders: 16
    maxReplicationSlots: 16
