# SPDX-License-Identifier: Apache-2.0
architecture: replication

replication:
  primary:
    persistence:
      enabled: false
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: false

pdb:
  enabled: true
  minAvailable: 1
