{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.pdb.enabled (or (include "valkey.isReplication" .) (include "valkey.isSentinel" .) (include "valkey.isCluster" .)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
  {{- include "valkey.renderAnnotations" (dict "root" .) | nindent 2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "valkey.valkeyLabels" (dict "root" .) | nindent 6 }}
{{- end }}
{{- if and .Values.pdb.enabled (include "valkey.isSentinel" .) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "valkey.sentinelStatefulSetName" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
  {{- include "valkey.renderAnnotations" (dict "root" .) | nindent 2 }}
spec:
  minAvailable: {{ .Values.sentinel.quorum }}
  selector:
    matchLabels:
      {{- include "valkey.sentinelLabels" . | nindent 6 }}
{{- end }}
