{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.secretName" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- include "valkey.renderAnnotations" (dict "root" .) | nindent 2 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ include "valkey.password" . | quote }}
{{- end }}
