{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valkey.serviceAccountName" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- include "valkey.renderAnnotations" (dict "root" . "annotations" .Values.serviceAccount.annotations) | nindent 2 }}
{{- end }}
