# SPDX-License-Identifier: Apache-2.0
architecture: cluster

cluster:
  minInSyncReplicas: 2
  controllers:
    replicaCount: 3
    persistence:
      size: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 2Gi
  brokers:
    replicaCount: 0  # Combined mode: each controller acts as both controller and broker

pdb:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
