# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061).
# auth.existingSecret is required when externalSecrets.enabled=true.
architecture: standalone

standalone:
  persistence:
    enabled: false

auth:
  enabled: true
  existingSecret: my-valkey-auth

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: valkey-password
      remoteRef:
        key: test/password
