# SPDX-License-Identifier: Apache-2.0
architecture: standalone

auth:
  enabled: true
  password: ci-valkey-password

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
