# SPDX-License-Identifier: Apache-2.0
architecture: cluster

auth:
  enabled: true
  password: ci-valkey-password

tls:
  enabled: true
  existingSecret: valkey-tls
  insecureSkipVerify: true

cluster:
  nodes: 6
  replicasPerMaster: 1
  persistence:
    enabled: false

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: valkey-tls
    type: Opaque
    stringData:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDhjCCAm6gAwIBAgIUEg5O8TyQujrfSLX88ZPBH8hzkxIwDQYJKoZIhvcNAQEL
        BQAwETEPMA0GA1UEAwwGdmFsa2V5MB4XDTI2MDYxNTE2MjU0N1oXDTM2MDYxMjE2
        MjU0N1owETEPMA0GA1UEAwwGdmFsa2V5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        MIIBCgKCAQEAsv+wQx1xxRTkSLrHIoy2F311zsgFWt+JpH+VyqYIeNHQF2AMZQ7W
        cXj7To7a3bWNdw5AZRbi3KtIgebT3M7wP/V1Xy+eTmmdWVoy/av5vgDeGsanMfGJ
        BRz8+KIHrSb44VPRUXnrkLrfma8tfLDJjNUCjNX0E5KcKhNfdNts8V52r8pi9fio
        zVFz+WGHd20hjroHjLV8BnMBVrzfP1pjxgbjBJbubg4VlZ5iQF/AyhzERpigiLVn
        NVZ2FVfMxPX13ie5ph0wXeMwLEmW0SerYfn628uakZl+aO5SpYCEmPgRsr6VsmDY
        Za1vZdHxMS2g0lt4R8BzZ7Xq9VXugxXYcwIDAQABo4HVMIHSMB0GA1UdDgQWBBRD
        UvXveALcY47E7r5jC0mRi+lW2DAfBgNVHSMEGDAWgBRDUvXveALcY47E7r5jC0mR
        i+lW2DAPBgNVHRMBAf8EBTADAQH/MH8GA1UdEQR4MHaCBnZhbGtleYIOdmFsa2V5
        LXByaW1hcnmCDXZhbGtleS1jbGllbnSCD3ZhbGtleS1oZWFkbGVzc4IrKi52YWxr
        ZXktaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0
        hwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQBzVrpaPQ8gyzQIO+5fgr/HxPaASJ+h
        Vf0d62v/VcTO57+q2GOpYiffpeg7hHwlKCQsx87ihSDGytJGWcfrpc8lqELxhPaJ
        LPwArAblQHWSGoRy28T8TOqnCqjd22VG2Ecbd2JIG/ZnYTa0yhXwRVh5XPhiW+Gr
        hCYi7/J83Bow9TbWJ0WyaYp57zjciwzWrYYJicSDSLu+aCDMqaJt7cTkbBVX+y0+
        lxiM3Nf1xAPVd15TiA/JevhGc/xAp0diMpd9gDdVLvmFcXXBDkIz1EsSvJGYtTdb
        u75YqU/vPF+UzD3KSUmoGsxQt4/sEQxlcqQW2r1710tjxHCQ7B8BVxq4
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCy/7BDHXHFFORI
        uscijLYXfXXOyAVa34mkf5XKpgh40dAXYAxlDtZxePtOjtrdtY13DkBlFuLcq0iB
        5tPczvA/9XVfL55OaZ1ZWjL9q/m+AN4axqcx8YkFHPz4ogetJvjhU9FReeuQut+Z
        ry18sMmM1QKM1fQTkpwqE19022zxXnavymL1+KjNUXP5YYd3bSGOugeMtXwGcwFW
        vN8/WmPGBuMElu5uDhWVnmJAX8DKHMRGmKCItWc1VnYVV8zE9fXeJ7mmHTBd4zAs
        SZbRJ6th+frby5qRmX5o7lKlgISY+BGyvpWyYNhlrW9l0fExLaDSW3hHwHNnter1
        Ve6DFdhzAgMBAAECggEAU1I/D7bEjzte2lYLPRNn7b5KWON1zquwbCCxrt+joO31
        ofPlQSNrge2Reat4yOxqeelp40SIfLTEbyduJmIzpmoRZSoK1DBIfN/GTZvAiIfp
        22fuSwrGP9mTDf+KeDjkcCrujDEnDLtYOzc2gszePQ6ofbtYPsYnqFRVQlWjvCR1
        WX84LNzv5toqUYQbNjJOjmnlaUzxJVGYld9TEfO0x4D40jnLxHxs1rtucmajcj4b
        flkagW/+AjNWpfCK3OHr3CC4aHKWozbwpK9GYabTfx5x5akXk7D/9dy89i5q4ecH
        p8WGG7HxySospnGe5vn3axAWHCOIPoy3h75TTiIxyQKBgQD7UPabyOISl4Yzr1s7
        s1b7Dvwi1KXt8ly/VhPN+63bpgUyc5YEFFmcAGGxJADLkeLdzaQ5G2x/rPhUp3uk
        2m5co8TQ1PEYIpWZWElFHbr1eV3uZT5sKgyUJAGBRQxdCtS2adYAJUQsECxS1mdM
        kQdFSnwB4jafqvkudWdamdl22wKBgQC2VbJRrf/4EjiePZfOKmBeRbOH/VOjDi+C
        VVDxZh+iSMRW/PCz63ZS2IPQVVho1AiX19JQa7t69st1VKzOw4on7YBY2TP9kIt7
        ppUEyaxinRBuseW5S+yqtCAa3gtTT5IXpUHWvW0v45irIii+pKHP73JlC4UZcRyr
        RrTOFikcSQKBgEChY6pQkQMjAJpOIHJL/rR1+BWlBj8ZMwzpwBIbBW0VVwTQgOXv
        rdPWrUj271Vq4SMVfYRKLy7udraek8ejfPpKC5WBDbedPUfAUqd5q9jxK1zhoJoE
        flOipthtv242GNoIgcZrzwpd5mgvR0WDjpEdRKLfYBjTyV1PSBMeubQ9AoGBAJ1o
        yjMdpjeBc4OY5O9FQkDgp6clGglQe89m3CQq5/BwJaB7aUnKYzIOXW2D4HlPY8PC
        vHxVJVt4qBk46p7tzN2/eeg6S1oCaYhsPYYOnVXdBoyp5Ard8wlDy9umCdz4esUT
        FA3RJuwK7of/S3GaK1+Z9gYptdRLBFcRCZJJK2CRAoGBAMzhq+1j9CMTK5soi/+6
        WnBDpPSUteOCJ5nJQwFSB71w7WKWgrPiPaLew3YkdAvKrRoHZ+M+IEMhXKKBMuX1
        Q84JOb3aYAm3pbWPRikfO+oXGSWuYlXhpbzv6tiAasJv090dyJU5lGZdME3uwQs+
        Zo0L5gf0dhXz3XadjgfqMHg2
        -----END PRIVATE KEY-----
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDhjCCAm6gAwIBAgIUEg5O8TyQujrfSLX88ZPBH8hzkxIwDQYJKoZIhvcNAQEL
        BQAwETEPMA0GA1UEAwwGdmFsa2V5MB4XDTI2MDYxNTE2MjU0N1oXDTM2MDYxMjE2
        MjU0N1owETEPMA0GA1UEAwwGdmFsa2V5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        MIIBCgKCAQEAsv+wQx1xxRTkSLrHIoy2F311zsgFWt+JpH+VyqYIeNHQF2AMZQ7W
        cXj7To7a3bWNdw5AZRbi3KtIgebT3M7wP/V1Xy+eTmmdWVoy/av5vgDeGsanMfGJ
        BRz8+KIHrSb44VPRUXnrkLrfma8tfLDJjNUCjNX0E5KcKhNfdNts8V52r8pi9fio
        zVFz+WGHd20hjroHjLV8BnMBVrzfP1pjxgbjBJbubg4VlZ5iQF/AyhzERpigiLVn
        NVZ2FVfMxPX13ie5ph0wXeMwLEmW0SerYfn628uakZl+aO5SpYCEmPgRsr6VsmDY
        Za1vZdHxMS2g0lt4R8BzZ7Xq9VXugxXYcwIDAQABo4HVMIHSMB0GA1UdDgQWBBRD
        UvXveALcY47E7r5jC0mRi+lW2DAfBgNVHSMEGDAWgBRDUvXveALcY47E7r5jC0mR
        i+lW2DAPBgNVHRMBAf8EBTADAQH/MH8GA1UdEQR4MHaCBnZhbGtleYIOdmFsa2V5
        LXByaW1hcnmCDXZhbGtleS1jbGllbnSCD3ZhbGtleS1oZWFkbGVzc4IrKi52YWxr
        ZXktaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0
        hwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQBzVrpaPQ8gyzQIO+5fgr/HxPaASJ+h
        Vf0d62v/VcTO57+q2GOpYiffpeg7hHwlKCQsx87ihSDGytJGWcfrpc8lqELxhPaJ
        LPwArAblQHWSGoRy28T8TOqnCqjd22VG2Ecbd2JIG/ZnYTa0yhXwRVh5XPhiW+Gr
        hCYi7/J83Bow9TbWJ0WyaYp57zjciwzWrYYJicSDSLu+aCDMqaJt7cTkbBVX+y0+
        lxiM3Nf1xAPVd15TiA/JevhGc/xAp0diMpd9gDdVLvmFcXXBDkIz1EsSvJGYtTdb
        u75YqU/vPF+UzD3KSUmoGsxQt4/sEQxlcqQW2r1710tjxHCQ7B8BVxq4
        -----END CERTIFICATE-----
