# SPDX-License-Identifier: Apache-2.0
architecture: cluster
cluster:
  minInSyncReplicas: 2
  controllers:
    replicaCount: 3
    persistence:
      size: 50Gi
  brokers:
    replicaCount: 0
pdb:
  enabled: true
