apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-sit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: sit-project
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: 'https://github.com/tondy-reslve/k8s-helm-gitops.git'
    targetRevision: HEAD
    path: charts/kafka
    helm:
      valueFiles:
        - ../../middleware/kafka/values-sit.yaml
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind