apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Chart.Name }}-svc
  namespace: {{ .Values.env }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    env: {{ .Values.env }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP