# SPDX-License-Identifier: Apache-2.0
architecture: cluster

auth:
  enabled: true
  password: ci-redis-password

cluster:
  nodes: 6
  replicasPerMaster: 1
  persistence:
    enabled: true
    size: 2Gi

pdb:
  enabled: true
