# SPDX-License-Identifier: Apache-2.0
# CI scenario: dual-stack policy for Redis standalone (GR-058)
architecture: standalone

standalone:
  persistence:
    enabled: false

service:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
