# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  enabled: true
  existingSecret: external-redis-auth
  existingSecretPasswordKey: password

replication:
  replicaCount: 1

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: external-redis-auth
    type: Opaque
    stringData:
      password: ci-redis-password
