# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  enabled: true
  password: ci-redis-password

replication:
  replicaCount: 2
  primary:
    persistence:
      enabled: true
      size: 2Gi
  replica:
    persistence:
      enabled: true
      size: 2Gi

pdb:
  enabled: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: redis
