certificates:
  sit-crt:
    namespace: my-app-sit
    commonName: "*.my-app-sit.svc.cluster.local"
    dnsNames:
      # Keycloak
      - "keycloak.my-app-sit.svc.cluster.local"
      - "keycloak-sit.my-app-sit.svc"
      - "keycloak-sit.my-app-sit.svc.cluster.local"
      # Redis
      - "redis.my-app-sit.svc"
      - "redis.my-app-sit.svc.cluster.local"
      - "*.redis-headless.my-app-sit.svc.cluster.local"
      - "*.redis-sentinel.my-app-sit.svc.cluster.local"
      # Valkey
      - "valkey-sit.my-app-sit.svc"
      - "valkey-sit.my-app-sit.svc.cluster.local"
      - "*.valkey-sit-headless.my-app-sit.svc.cluster.local"
      - "*.valkey-sit-sentinel.my-app-sit.svc.cluster.local"
      # Common
      - "localhost"

  backend-truststore:
    namespace: sit-backend
    commonName: "sit-backend.sit-backend.svc.cluster.local"
    dnsNames:
      - "sit-backend.sit-backend.svc.cluster.local"
    keystores:
      pkcs12:
        create: true
        password: "changeit"