certificates:
  redis-crt:
    namespace: my-app-sit
    vaultRole: redis-sit-role
    dnsNames:
      - "redis.my-app-sit.svc"
      - "redis.my-app-sit.svc.cluster.local"
      - "*.redis-headless.my-app-sit.svc.cluster.local"
      - "*.redis-sentinel.my-app-sit.svc.cluster.local"
      - "localhost"

  valkey-crt:
    namespace: my-app-sit
    vaultRole: valkey-sit-role
    dnsNames:
    - "valkey-sit.my-app-sit.svc"
    - "valkey-sit.my-app-sit.svc.cluster.local"
    - "*.valkey-sit-headless.my-app-sit.svc.cluster.local"
    - "valkey-sit-sentinel.my-app-sit.svc.cluster.local"
    - "*.valkey-sit-sentinel.my-app-sit.svc.cluster.local"
    - "localhost"