certificates:
  uat-crt:
    namespace: my-app-uat
    commonName: "*.my-app-uat.svc.cluster.local"
    dnsNames:
      # Keycloak
      - "keycloak.my-app-uat.svc.cluster.local"
      - "keycloak-uat.my-app-uat.svc"
      - "keycloak-uat.my-app-uat.svc.cluster.local"
      # Redis
      - "redis.my-app-uat.svc"
      - "redis.my-app-uat.svc.cluster.local"
      - "*.redis-headless.my-app-uat.svc.cluster.local"
      - "*.redis-sentinel.my-app-uat.svc.cluster.local"
      # Valkey
      - "valkey-uat.my-app-uat.svc"
      - "valkey-uat.my-app-uat.svc.cluster.local"
      - "*.valkey-uat-headless.my-app-uat.svc.cluster.local"
      - "*.valkey-uat-sentinel.my-app-uat.svc.cluster.local"
      # Common
      - "localhost"