{{- range $certName, $config := .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certName }}
  namespace: {{ $config.namespace }}
spec:
  secretName: {{ $certName }}
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: {{ $config.commonName | default (index $config.dnsNames 0) | quote }}
  dnsNames:
    {{- toYaml $config.dnsNames | nindent 4 }}
{{- end }}

{{- if .Values.backend-truststore }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-ca-config
  namespace: {{ .Values.backend-truststore.namespace }}
data:
  ca.crt: |
{{ .Values.backend-truststore.caPem | indent 4 }}
{{- end }}