caSecret:
  namespaces:
    - vault
    - my-app-sit
    - my-app-uat
    - test-ca-secret
    - sit-backend

vault:
  server:
    enabled: false
  ui:
    enabled: false

  global:
    externalVaultAddr: "https://vault.infra.local:30443"
    
  injector:
    enabled: true
    nodeSelector:
      pool: infra
    hostAliases:
      - ip: "192.168.118.254"
        hostnames:
          - "vault.infra.local"
    resources:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 250m, memory: 128Mi }
    agentDefaults:
      cpuRequest: 50m
      cpuLimit: 250m
      memRequest: 64Mi
      memLimit: 128Mi

vault-secrets-operator:
  defaultVaultConnection:
    enabled: true
    address: "https://vault.infra.local:30443"
    skipTLSVerify: false
    caCertSecret: "vault-ca-secret"
  defaultAuthMethod:
    enabled: true
    method: kubernetes
    mount: kubernetes
    kubernetes:
      role: "vso-role"
      serviceAccount: "vault-plugins-vault-secrets-operator-controller-manager"
  controller:
    hostAliases:
    - ip: "192.168.118.254"
      hostnames:
        - "vault.infra.local"
    kubeRbacProxy:
      image:
        repository: "quay.io/brancz/kube-rbac-proxy"
        tag: "v0.15.0"
      resources:
        requests: { cpu: 5m, memory: 32Mi }
        limits:   { cpu: 100m, memory: 64Mi }
    manager:
      resources:
        requests: { cpu: 10m, memory: 64Mi }
        limits:   { cpu: 500m, memory: 128Mi }