vault:
  server:
    enabled: false
  ui:
    enabled: false

  global:
    externalVaultAddr: "https://vault.infra.local:30443"
    
  injector:
    enabled: true
    nodeSelector:
      pool: infra
    hostAliases:
      - ip: "192.168.118.254"
        hostnames:
          - "vault.infra.local"
    agentDefaults:
      extraVolumes:
        - name: vault-ca-vol
          secret:
            secretName: vault-ca-secret
      extraVolumeMounts:
        - name: vault-ca-vol
          mountPath: /vault/tls
          readOnly: true
      extraEnvironmentVars:
        VAULT_CACERT: "/vault/tls/ca.crt"

vault-secrets-operator:
  defaultVaultConnection:
    enabled: true
    address: "https://vault.infra.local:30443"
    skipTLSVerify: false
    caCertSecret: "vault-ca-secret"
  hostAliases:
    - ip: "192.168.118.254"
      hostnames:
        - "vault.infra.local"
  controller:
    kubeRbacProxy:
      image:
        repository: "quay.io/brancz/kube-rbac-proxy"
        tag: "v0.15.0"