{{- range .Values.caSecret.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-ca-secret
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDzjCCAragAwIBAgIUTTC0+jQeFE8F+sH2M+ht2FoyOJQwDQYJKoZIhvcNAQEL
    BQAwJjEkMCIGA1UEAxMbaW5mcmEubG9jYWwgQ2x1c3RlciBSb290IENBMB4XDTI2
    MDgyODA5MTgxN1oXDTI2MTEyNjA5MTg0N1owADCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAL0qm/19JysIetJlK5erPp+XZWyMpEeODpVUE/J3c0rc2Dtj
    f43H6P+xWRQYcH9RE3rZFTropFsasmHSznOuZgZQCAG8NTCFBo9QUQS2tAClBDov
    7iQHQW5gydvItmz8+1oHSeTtKHSxW0eSHukspfiN9G8hz0dxT4J+QsfotEsFVJgD
    lcihyiDtpR02FYydBBggM1pizC3J2kHarrqRM2wwqxtihh6dvn3t1ZZsUgS7snDD
    obabBfJvGadUgrF+o5sU0tGuYJ3SH3w4R+4pI6uo6p6BfyXTXtHxqnljbc4JC/JD
    ZDiigGLArWBTeufS+4eLEj6d3sSuZRZbfJmdzwECAwEAAaOCARgwggEUMA4GA1Ud
    DwEB/wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0O
    BBYEFLFQ2jbuCcRw+odsPrbviZ6pHk9gMB8GA1UdIwQYMBaAFILTy2MfNgKwiWZD
    bvk7o1Nk60B3MEUGCCsGAQUFBwEBBDkwNzA1BggrBgEFBQcwAoYpaHR0cHM6Ly92
    YXVsdC5pbmZyYS5sb2NhbDozMDQ0My92MS9wa2kvY2EwHwYDVR0RAQH/BBUwE4IR
    dmF1bHQuaW5mcmEubG9jYWwwOwYDVR0fBDQwMjAwoC6gLIYqaHR0cHM6Ly92YXVs
    dC5pbmZyYS5sb2NhbDozMDQ0My92MS9wa2kvY3JsMA0GCSqGSIb3DQEBCwUAA4IB
    AQDOxE0EOpiRUF2FX5g3VE+qrrwbP2ubRYuvk3VwIydP/RLz7QDFxgjzImyYHb2o
    qJX8v1gTcr1aI/FWW/cR0QfrtLys7bA/LnjbcjSKDQSDfvC99p/L2qt81JhP2VRb
    zwG3VZpYHJRjlgBcJ8D6iWLjI6FPrME+m96VysNIv51rAcu6OB4OgcEXmTAEElxk
    03Pj8in/qYCwWUg/8Y7Bio2Ven5JAn1GU4CyKJbJ8XJ40N3RxKu6xJiz9faRQtw6
    7qa9t7Fy9x2MAHgymE62a2LyoDQaVpWsSbtNNyJR+Jfxr7wcpS28maZimbXMhzhX
    qU0kZlGgrvIQ99fWJm5Mr5oG
    -----END CERTIFICATE-----
{{- end }}