architecture: sentinel

image:
  repository: docker.io/library/redis
  tag: "6.2.23"
  pullPolicy: IfNotPresent

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "my-app-uat-role"
  vault.hashicorp.com/tls-skip-verify: "false"
  vault.hashicorp.com/namespace: "admin"

  vault.hashicorp.com/agent-inject-secret-redis-password: "secret/data/uat/redis"
  vault.hashicorp.com/agent-inject-template-redis-password: |
    {{- with secret "secret/data/uat/redis" -}}
    {{ index .Data.data "redis-password" }}
    {{- end -}}

auth:
  enabled: true

tls:
  enabled: true
  existingSecret: "uat-crt"
  certFilename: tls.crt
  keyFilename: tls.key
  caFilename: ca.crt

replication:
  primary:
    persistence:
      storageClass: "longhorn-uat"
      size: 2Gi
  replica:
    persistence:
      storageClass: "longhorn-uat"
      size: 2Gi

# -- Node selector for pod scheduling
nodeSelector: 
  pool: uat
# -- Tolerations for pod scheduling
tolerations: 
  - key: "env"
    operator: "Equal"
    value: "uat"
    effect: "NoSchedule"